### ISSUE TITLE
A cdm_source table with zero rows causes executeDqChecks to fail

### ISSUE THREAD

**Issue by ablack3** [OHDSI/DataQualityDashboard#173] opened 2020-09-03 21:08 UTC
I was trying to run DQ and getting a really strange error. 

`Error in $<-.data.frame(tmp, DQD_VERSION, value = "1.0.0"): replacement has 1 row, data has 0`

It turns out that my cdm_source table had not been populated which was causing the error. If the cdm_source table has zero rows then it would be nice if the data quality checks flagged this as a potential problem.

``` r
library(DataQualityDashboard)
#> Loading required package: DatabaseConnector

cd <- Eunomia::getEunomiaConnectionDetails()
con <- connect(cd)
#> Connecting using SQLite driver
dbSendQuery(con, "DELETE FROM main.cdm_source;")
#> <SQLiteResult>
#>   SQL  DELETE FROM main.cdm_source;
#>   ROWS Fetched: 0 [complete]
#>        Changed: 1
dbGetQuery(con, "select * from main.cdm_source")
#> Warning: Closing open result set, pending rows
#>  [1] CDM_SOURCE_NAME                CDM_SOURCE_ABBREVIATION       
#>  [3] CDM_HOLDER                     SOURCE_DESCRIPTION            
#>  [5] SOURCE_DOCUMENTATION_REFERENCE CDM_ETL_REFERENCE             
#>  [7] SOURCE_RELEASE_DATE            CDM_RELEASE_DATE              
#>  [9] CDM_VERSION                    VOCABULARY_VERSION            
#> <0 rows> (or 0-length row.names)

DataQualityDashboard::executeDqChecks(connectionDetails = cd, 
                                      cdmDatabaseSchema = "main", 
                                      resultsDatabaseSchema = "temp",
                                      cdmSourceName = "Eunomia", 
                                      checkLevels = "TABLE",
                                      writeToTable = F)
#> Connecting using SQLite driver
#> Connecting using SQLite driver
#> Error in `$<-.data.frame`(`*tmp*`, "DQD_VERSION", value = "1.0.0"): replacement has 1 row, data has 0




# The error is caused by this line in the .summarizeResults function
metadata <- querySql(con, "select * from main.cdm_source;")
metadata$DQD_VERSION <- as.character(packageVersion("DataQualityDashboard"))
#> Error in `$<-.data.frame`(`*tmp*`, DQD_VERSION, value = "1.0.0"): replacement has 1 row, data has 0

disconnect(con)
sessionInfo()
#> R version 3.5.3 (2019-03-11)
#> Platform: x86_64-pc-linux-gnu (64-bit)
#> Running under: Amazon Linux AMI 2018.03
#> 
#> Matrix products: default
#> BLAS: /usr/lib64/R/lib/libRblas.so
#> LAPACK: /usr/lib64/R/lib/libRlapack.so
#> 
#> locale:
#>  [1] LC_CTYPE=en_US.UTF-8          LC_NUMERIC=C                 
#>  [3] LC_TIME=en_US.UTF-8           LC_COLLATE=en_US.UTF-8       
#>  [5] LC_MONETARY=en_US.UTF-8       LC_MESSAGES=en_US.UTF-8      
#>  [7] LC_PAPER=en_US.UTF-8          LC_NAME=en_US.UTF-8          
#>  [9] LC_ADDRESS=en_US.UTF-8        LC_TELEPHONE=en_US.UTF-8     
#> [11] LC_MEASUREMENT=en_US.UTF-8    LC_IDENTIFICATION=en_US.UTF-8
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#> [1] magrittr_1.5               DataQualityDashboard_1.0.0
#> [3] DatabaseConnector_3.0.0   
#> 
#> loaded via a namespace (and not attached):
#>  [1] Rcpp_1.0.5           knitr_1.23           tidyselect_1.1.0    
#>  [4] bit_4.0.4            R6_2.4.1             rlang_0.4.7         
#>  [7] dplyr_1.0.2          stringr_1.4.0        blob_1.2.1          
#> [10] highr_0.8            tools_3.5.3          xfun_0.8            
#> [13] DBI_1.1.0            SqlRender_1.6.8      ellipsis_0.3.1      
#> [16] htmltools_0.3.6      yaml_2.2.0           bit64_4.0.4         
#> [19] digest_0.6.25        tibble_3.0.3         lifecycle_0.2.0     
#> [22] crayon_1.3.4         rJava_0.9-13         Eunomia_1.0.0       
#> [25] purrr_0.3.4          ParallelLogger_2.0.0 vctrs_0.3.4         
#> [28] glue_1.4.2           memoise_1.1.0        evaluate_0.14       
#> [31] RSQLite_2.2.0.9000   rmarkdown_1.13       stringi_1.4.6       
#> [34] pillar_1.4.6         compiler_3.5.3       generics_0.0.2      
#> [37] pkgconfig_2.0.3
```

<sup>Created on 2020-09-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by clairblacketer** [comment] 2020-11-02 13:45
@fdefalco agreed. Perhaps a different discussion but I would also like to have a way to save progress, kind of like cohortMethod does so if something does cause the program to exit the initial checks that were resolved don't have to be done again.

**Comment by DaveBarman** [comment] 2020-12-01 19:39
Hi @clairblacketer is this a duplicate of #171? Seems like it is the same issue.

**Closed** 2021-02-25 15:50 UTC
