### ISSUE TITLE
Warning: Error in convertJsonResultsFileCase: could not find function "convertJsonResultsFileCase"

### ISSUE THREAD

**Issue by vittoriaramella** [OHDSI/DataQualityDashboard#459] opened 2023-06-05 15:20 UTC
Hi everyone,

After updating the package to the latest version (2.3.0), I encountered an issue. When I attempt to view the results of the DQD using the `viewDqDashboard` function, I receive the following error message:

`Warning: Error in convertJsonResultsFileCase: could not find function "convertJsonResultsFileCase"
  46: observe [/usr/lib64/R/library/DataQualityDashboard/shinyApps/app.R#5]
  45: <observer>
   2: shiny::runApp
   1: DataQualityDashboard::viewDqDashboard`

It appears that there is an attempt to call the new `convertJsonResultsFileCase` function, but upon inspecting the code of `viewDqDashboard`, I couldn't locate where this occurs. I may be missing something or looking in the wrong place for a solution.

I appreciate any insights or guidance you can provide to resolve this issue.

Thank you,
Vittoria

**Comment by katy-sadowski** [comment] 2023-06-05 16:02
Hi @vittoriaramella , thanks for this report!  I believe I see what the issue is and will work to ship a fix quickly (for reference, the function is called [here](https://github.com/OHDSI/DataQualityDashboard/blob/741f748d9d940577a1ea57eb562bd763281ba662/inst/shinyApps/app.R#L5) and I think it needs to have the package name added to the call to avoid the error you're seeing).

In the meantime, I _think_ that if you run `library(DataQualityDashboard)` before calling the `viewDqDashboard` function, you should resolve this issue.  Let me know if you can try that & if it works :)

Thanks!

**Comment by vittoriaramella** [comment] 2023-06-06 07:21
Thank you @katy-sadowski ! As you suggested, I added `library(DataQualityDashboard)` at the beginning of my script instead of using `DataQualityDashboard::viewDqDashboard`, and it worked successfully!

**Comment by katy-sadowski** [comment] 2023-07-27 01:30
This has been fixed in the latest release.

**Closed by katy-sadowski** 2023-07-27 01:30 UTC
Labels: bug
